MODEL1:

  low_wave: 1
  high_wave: 100

  species:
    - 'TiO2'
    - 'Fe'
    - 'Mg2SiO4'

  files:
    - 'vmodel100rad_logmodel1_low.keras'
    - 'vmodel100rad_logmodel1_mid.keras'
    - 'vmodel100rad_logmodel1_high.keras'

MODEL2:

  low_wave: 1
  high_wave: 100

  species:
    - 'TiO2'
    - 'Fe'
    - 'MgSiO3'

  files:
    - 'vmodelens_logmodel1_low.keras'
    - 'vmodelens_logmodel1_mid.keras'
    - 'vmodelens_logmodel1_high.keras'

MODEL3:

  low_wave: 1
  high_wave: 100

  species:
    - 'SiO2'
    - 'MgSiO3'
    - 'Mg2SiO4'

  files:
    - 'vmodelsil_logmodel1_low.keras'
    - 'vmodelsil_logmodel1_mid.keras'
    - 'vmodelsil_logmodel1_high.keras'

MODEL4:

  low_wave: 1
  high_wave: 100

  species:
    - 'SiO2'
    - 'MgSiO3'
    - 'Fe'

  files:
    - 'vmodelmeteor_log_model2_low.keras'
    - 'vmodelmeteor_log_model2_mid.keras'
    - 'vmodelmeteor_log_model2_high.keras'