MODEL1:

  low_wave: 1
  high_wave: 100
  scale: 'norm'

  files:
    - 'vmodel100rad_model11_low.keras'
    - 'vmodel100rad_model11_mid.keras'
    - 'vmodel100rad_model11_high.keras'

MODEL2:

  low_wave: 1
  high_wave: 100
  scale: 'norm'

  files:
    - 'vmodelens_model2_low.keras'
    - 'vmodelens_model2_mid.keras'
    - 'vmodelens_model2_high.keras'

MODEL3:

  low_wave: 1
  high_wave: 100
  scale: 'norm'

  files:
    - 'vmodelsil_model1_low.keras'
    - 'vmodelsil_model1_mid.keras'
    - 'vmodelsil_model1_high.keras'

MODEL4:

  low_wave: 1
  high_wave: 100
  scale: 'log'

  files:
    - 'vmodelmeteor_log_model1_low.keras'
    - 'vmodelmeteor_log_model1_mid.keras'
    - 'vmodelmeteor_log_model1_high.keras'